name: Build API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      id: date
      run: dotnet build --no-restore -c Release && echo "::set-output name=today::$(date +"%d-%m-%y--%H-%M-%S")"
    - name: Upload Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
            D:\a\PrayerTimesAPI\PrayerTimesAPI\bin\Release\net6.0-windows10.0.19041.0\API.dll
            D:\a\PrayerTimesAPI\PrayerTimesAPI\libs\*
        name: PrayerAPI Auto-Build
        tag_name: "${{ steps.date.outputs.today }}--Windows-10"
